baseurl: https://qiaoin.github.io
languageCode: en-us
title: 在桥边
theme: hugo-lithium
hasCJKLanguage: true
googleAnalytics: 'G-EBLEJGMMQV'
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: 重学基础
      url: /re-learning-cs/
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: GitHub
      url: https://github.com/qiaoin
      weight: 3
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: 在桥边
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - awk
    - bash
    - c
    - c++
    - cmake
    - go
    - html
    - java
    - javascript
    - python
    - rust
    - typescript
    - yaml
  highlightjsTheme: monokai
  highlightjsVersion: 10.7.1
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  utteranc:
    enable: true
    repo: "qiaoin/hugo-blog-comments" # 存储评论的Repo，格式为 owner/repo
    issueTitle: "og:title"            # 表示你选择以那种方式让github issue的评论和你的文章关联可以选择默认的pathname。
    theme: "github-light"             # 样式主题
