baseurl: https://qiaoin.github.io
languageCode: en-us
title: 在桥边
theme: hugo-lithium
hasCJKLanguage: true
googleAnalytics: 'G-EBLEJGMMQV'
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Rust 100
      url: /leetcode-rust-100/
      weight: 1
    - name: 重学基础
      url: /re-learning-cs/
      weight: 2
    - name: Readings
      url: /readings/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: GitHub
      url: https://github.com/qiaoin
      weight: 5
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: 在桥边
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - awk
    - bash
    - c
    - c++
    - cmake
    - go
    - html
    - java
    - javascript
    - python
    - rust
    - typescript
    - yaml
  highlightjsTheme: monokai
  highlightjsVersion: 10.7.1
  customCSS: ["css/custom.css"]
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  giscus:
    enable: true
    repo: "qiaoin/qiaoin.github.io"  # 当前项目，使用 Discussions 作为评论系统
    mappingType: "pathname"          # 页面与嵌入的 discussion 之间的映射关系
    theme: "light"                   # 样式主题
